#!/bin/sh

DIRNAME="$(dirname $0)"
if [ -e $DIRNAME/day$1/index.js ]; then
  echo "Day $1 files are already set up"
else
  if [ ! -e $DIRNAME/day$1 ]; then
    mkdir $DIRNAME/day$1
  fi
  cp $DIRNAME/template/* $DIRNAME/day$1
  touch $DIRNAME/day$1/input 
fi